<?php
/**
 * Default Russian Lexicon Entries for modxTalks
 *
 * @package modxtalks
 * @subpackage lexicon
 */
$_lang['modxtalks'] = 'modxTalks';
$_lang['modxtalks.add'] = 'Добавить';
$_lang['modxtalks.add_comment'] = 'Добавить комментарий';
$_lang['modxtalks.atributes'] = 'Атрибуты';
$_lang['modxtalks.ajax_request_pending'] = 'Отправлен AJAX запрос, ожидаем ответа от сервера!';
$_lang['modxtalks.ajax_disconnected'] = 'Сервер не отвечает. <a href=\"javascript:jQuery.MTAjax.resumeAfterDisconnection()\">Попробуйте еще раз<\/a>, или <a href=\"\" onclick=\"window.location.reload();return false\">обновите страницу</a>.';
$_lang['modxtalks.ban'] = 'Забанить';
$_lang['modxtalks.ban_comment'] = 'Добавить IP-адресс в список блокировок IP, автоматически комментарий будет удалён';
$_lang['modxtalks.blocking_ip'] = 'Блокирование IP адреса';
$_lang['modxtalks.content'] = 'Комментарий';
$_lang['modxtalks.confirm_delete'] = 'Удалить комментарий навсегда?';
$_lang['modxtalks.comments'] = 'комментариев';
$_lang['modxtalks.comments_menu'] = 'Комментарии';
$_lang['modxtalks.comments_setting'] = 'Настройки комментариев';
$_lang['modxtalks.comments_total'] = 'комментарий';
$_lang['modxtalks.comments_totals'] = 'Всего комментариев';
$_lang['modxtalks.comments_delete'] = 'Удалённых комментариев';
$_lang['modxtalks.comments_unconfirmed'] = 'Не подтвержденные';
$_lang['modxtalks.comments_unconfirmed_desc'] = '<div id="comments_unconfirmed"><span></span></div>Не подтвержденные комментарии';
$_lang['modxtalks.comments_per_page'] = 'Комментариев на страницу';
$_lang['modxtalks.comments_per_page_desc'] = 'Максимальное количество комментариев на страницы для отображения при визуализации управления навигации по страницам.';
$_lang['modxtalks.confirm_discard_reply'] = 'Комментарий еще не отправлен, отменить все изменения?';
$_lang['modxtalks.confirmLeave'] = 'Вы не сохранили то, что вы редактируете! Если вы оставите эту страницу, вы потеряете все внесённые изменения. Разве это нормально?';
$_lang['modxtalks.conversation'] = 'Тема';
$_lang['modxtalks.conversations'] = 'Темы';
$_lang['modxtalks.default_desc'] = 'Оставьте не заполненным, если хотите использовать настройки по умолчанию.';
$_lang['modxtalks.default'] = 'по умолчанию';
$_lang['modxtalks.delet'] = 'Удалить';
$_lang['modxtalks.delet_comment'] = 'Удалить комментарий';
$_lang['modxtalks.delet_conversation'] = 'Удалить тему.';
$_lang['modxtalks.delet_conversation_desc'] = '<strong>ВНИМАНИЕ!</strong> При удалении темы, все комментарии будут удалены. <br /><strong>Удалить эту тему?</strong>';
$_lang['modxtalks.desc'] = 'Управление ModxTalks.';
$_lang['modxtalks.demo'] = 'Демо сайт';
$_lang['modxtalks.demo_desc'] = 'Демо сайт комментариев modxTalks.';
$_lang['modxtalks.description'] = 'Описание';
$_lang['modxtalks.desc_titl'] = 'Настройка комментариев для вашего ресурса. <br/>Вы можете изменить значения по умолчанию, которые заданные в системных настройках комментариев, для каждого ресурса индивидуально. <br /><strong class="alert-mt">Примечание.</strong> Вы можете просмотреть документацию во <a class="link-mt helpmodxtalks" href="#settings:modxtalks-settings" onClick="javascript:modxTalks.loadHelpPaneMT(\'ru/help.html\');">всплывающем окне</a>, или <a class="link-mt" target="_blank" href="http://modxtalks.artdevue.com/ru/help.html">открыть в новой вкладке</a>.';
$_lang['modxtalks.deleteTime'] = 'Дата удаления';
$_lang['modxtalks.delete'] = 'удалённые';
$_lang['modxtalks.default_template'] = 'шаблон по умолчанию';
$_lang['modxtalks.deleteUserId'] = 'Удалил';
$_lang['modxtalks.date_create'] = 'Дата добавления';
$_lang['modxtalks.editUserId'] = 'Отредактировал';
$_lang['modxtalks.editTime'] = 'Дата редактирования';
$_lang['modxtalks.goto_web'] = 'Перейти на страницу сайта.';
$_lang['modxtalks.help'] = 'Документация';
$_lang['modxtalks.help_desc'] = 'Документация комментариев по modxTalks.';
$_lang['modxtalks.items_empty_conversation_msg'] = '<h4>Нет записей, удовлетворяющих вашим критериям поиска</h4><p>Или вы еще не создали ни одной Темы с комментариями.</p>';
$_lang['modxtalks.items_empty_ip_msg'] = '<h4>Нет записей, удовлетворяющих вашим критериям поиска</h4><p>Или вы еще не добавили ни одного IP-адреса.</p>';
$_lang['modxtalks.items_empty_unconfirmed_msg'] = '<h4>Нет записей, удовлетворяющих вашим критериям поиска</h4><p>Или еще никто не опубликовал комментария на подтверждения.</p>';
$_lang['modxtalks.ipblock_desc'] = 'Управление IP-блокировками. Список IP-адресов, которые заблокированы. Это означает, что они не могут голосовать. <br/><strong class="alert-mt">Примечание.</strong> Вы можете настроить шаблоны с помощью символа *. --- Пример: заблокировать все IP-адреса, которые начинаются с "123.123.123."';
$_lang['modxtalks.ip_adress'] = 'IP адрес';
$_lang['modxtalks.ip_adress_desc'] = 'Заметка. описание, примечание...';
$_lang['modxtalks.ip_block_create'] = 'Добавить IP';
$_lang['modxtalks.ip_creat'] = 'Должно быть числовым IP-адресом';
$_lang['modxtalks.ip_remove'] = 'Удалить IP';
$_lang['modxtalks.ip_remove_confirm'] = 'Вы действительно хотите удалить этот IP-адрес?';
$_lang['modxtalks.ip_removes'] = 'Удалить IP адреса';
$_lang['modxtalks.ip_removes_confirm'] = 'Вы действительно хотите удалить все выбранные IP-адреса?';
$_lang['modxtalks.loading'] = 'Загрузка';
$_lang['modxtalks.management'] = 'modxTalks. Управление комментариями';
$_lang['modxtalks.management_desc'] = 'Здесь вы можете просмотреть информацию по каждой отельной теме комментария. Просмотреть не потверждённые комментарии, и при необходимости <a class="link-mt" href="#homeTab:not-confirmed">потвердить</a> в соответствующем разделе. В <a class="link-mt" href="#homeTab:ip-blocking">IP блокировки</a>, вы можете ввести IP адресс, чтобы запретить посетителю голосовать с таким IP адресом.';
$_lang['modxtalks.management_unconfirmed_desc'] = '<strong>Не подтвержденные комментарии.</strong> Вы можете управлять не потверждёнными комментариями, потвердить или удалить комметарий.<br />После потверждения, комментарий сразу появиться на вашем веб ресурсе, а юзеру, отправивший комметарий, придёт уведомление о добавлении на веб ресурс.';
$_lang['modxtalks.moderators'] = 'Модераторы';
$_lang['modxtalks.moderators_desc'] = 'Перечислите через запятую модераторов, которые имеют возможность модерировать комментарии в этом ресурсе.';
$_lang['modxtalks.menu_desc'] = 'Управления и подтверждение комментариев modxTalks.';
$_lang['modxtalks.more_text'] = 'Загрузить ещё';
$_lang['modxtalks.mute_conversation'] = 'Закрыть разговор';
$_lang['modxtalks.notifications'] = 'Уведомления';
$_lang['modxtalks.never'] = 'никогда';
$_lang['modxtalks.new_comment'] = 'Новых комментарий';
$_lang['modxtalks.not_confirmed'] = 'не подтвержденные';
$_lang['modxtalks.no_login'] = 'Авторизуйтесь на сайте, чтобы ответить.';
$_lang['modxtalks.opcions'] = 'Опции';
$_lang['modxtalks.post_err_nfs'] = 'Комментарий с таким ID не существует!';
$_lang['modxtalks.post'] = 'Комментарий';
$_lang['modxtalks.post_err_ae'] = 'A modxtalk with that name already exists.';
$_lang['modxtalks.post_err_nf'] = 'modxTalk не найден.';
$_lang['modxtalks.post_err_ns'] = 'modxTalk не указан.';
$_lang['modxtalks.post_err_ns_name'] = 'Пожалуйста, укажите название modxtalk.';
$_lang['modxtalks.post_err_remove'] = 'Произошла ошибка при попытке удалить modxtalk.';
$_lang['modxtalks.post_err_save'] = 'Произошла ошибка при попытке сохранить modxtalk.';
$_lang['modxtalks.post_err_data'] = 'Ошибка данных.';
$_lang['modxtalks.post_create'] = 'Создать новый modxTalk';
$_lang['modxtalks.post_remove'] = 'Удалить modxTalk';
$_lang['modxtalks.post_remove_confirm'] = 'Вы действительно хотите удалить modxtalk?';
$_lang['modxtalks.post_update'] = 'Обновить modxTalk';
$_lang['modxtalks.preview_checkbox'] = 'Предварительный просмотр';
$_lang['modxtalks.quote'] = 'Цитата';
$_lang['modxtalks.quote_text'] = 'Комментировать';
$_lang['modxtalks.resources_no'] = 'Ресурс не найден';
$_lang['modxtalks.resource_comments'] = 'Ресурс с комментариями';
$_lang['modxtalks.resource_comments_here'] = 'Дочерний ресурс с комментариями';
$_lang['modxtalks.select_comment'] = 'Выберите комментарий, чтобы посмотреть полное описание.';
$_lang['modxtalks.search...'] = 'Поиск...';
$_lang['modxtalks.time'] = 'Дата создания';
$_lang['modxtalks.title'] = 'Название';
$_lang['modxtalks.top_downloaded'] = 'Top Downloaded modxTalks';
$_lang['modxtalks.talks_selected_delete'] = 'Удалить выбранные';
$_lang['modxtalks.total'] = 'Всего';
$_lang['modxtalks.template_comment'] = 'Шаблон комментария';
$_lang['modxtalks.template_comment_desc'] = 'Шаблон для вывода комментариев.';
$_lang['modxtalks.template_deleting_comments'] = 'Шаблон удаленного комментария';
$_lang['modxtalks.template_deleting_comments_desc'] = 'Шаблон для вывода удалённых комментариев.';
$_lang['modxtalks.template_editing_comments'] = 'Шаблон редактирования комментария';
$_lang['modxtalks.template_editing_comments_desc'] = 'Шаблон для вывода редактирования комментариев.';
$_lang['modxtalks.template_authorization_comments'] = 'Шаблон авторизации в комментариях';
$_lang['modxtalks.template_authorization_comments_desc'] = 'Шаблон для вывода авторизации комментариев.';
$_lang['modxtalks.userId'] = 'Пользователь';
$_lang['modxtalks.unmute_conversation'] = 'Восстановить разговор';
$_lang['modxtalks.with_comments'] = ' с комментариями';
// BBCode
$_lang['modxtalks.bold'] = 'Жирный';
$_lang['modxtalks.fixed'] = 'Код';
$_lang['modxtalks.header'] = 'Заголовок';
$_lang['modxtalks.image'] = 'Изображение';
$_lang['modxtalks.italic'] = 'Курсив';
$_lang['modxtalks.link'] = 'Ссылка';
$_lang['modxtalks.strike'] = 'Зачеркнутый';
$_lang['modxtalks.video'] = 'Видео';
// setting name
$_lang['area'] = 'Раздел';
$_lang['area_highlight'] = 'Подсветка кода';
$_lang['area_settings'] = 'Общие настройки';
$_lang['area_settingBBCode'] = 'Настройка BBCode';
$_lang['area_emailNotifications'] = 'Почтовые уведомления';
// setting BBCode
$_lang['setting_modxtalks.editOptionsControls'] = 'Теги редактора';
$_lang['setting_modxtalks.editOptionsControls_desc'] = 'Выберите теги, для отображения иконок редактора. Доступные - fixed,image,link,strike,header,italic,bold,video,quote';
$_lang['setting_modxtalks.smileys'] = 'Смайлики';
$_lang['setting_modxtalks.smileys_desc'] = 'Включить отображение смайликов в комментариях?. Да / Нет';
$_lang['setting_modxtalks.detectUrls'] = 'Ссылки';
$_lang['setting_modxtalks.detectUrls_desc'] = 'Переводить адреса веб ресурсов в ссылки? Да / Нет';
// setting
$_lang['setting_modxtalks.add_timeout'] = 'Таймаут между отправкой комментариев';
$_lang['setting_modxtalks.add_timeout_desc'] = 'Время в секундах, между отправкой комментариев';
$_lang['setting_modxtalks.jquery'] = 'Включить jQuery';
$_lang['setting_modxtalks.jquery_desc'] = 'Если вы используете своё подключение jQuery для страницы, или используете сторонии сервисы, выбирите НЕТ, и убедитесь, что версия jQuery не ниже v1.7';
$_lang['setting_modxtalks.emailsFrom'] = 'Отправитель письма';
$_lang['setting_modxtalks.emailsFrom_desc'] = 'Адрес электронной почты, для указания отправителя в заголовке письма';
$_lang['setting_modxtalks.emailsReplyTo'] = 'Ответить на адрес';
$_lang['setting_modxtalks.emailsReplyTo_desc'] = 'Адрес электронной почты для ответа';
$_lang['setting_modxtalks.edit_time'] = 'Период редактирования комментария';
$_lang['setting_modxtalks.edit_time_desc'] = 'Время, после которого пользователь не может редактировать комментарий';
$_lang['setting_modxtalks.commentsPerPage'] = 'Количество комментариев';
$_lang['setting_modxtalks.commentsPerPage_desc'] = 'Максимальное количество комментариев на страницы для отображения при визуализации управления навигации по страницам.';
$_lang['setting_modxtalks.mtGravator'] = 'Использовать граватар';
$_lang['setting_modxtalks.mtGravator_desc'] = 'Включить граватар в сообщениях пользователей. Да / Нет';
$_lang['setting_modxtalks.mtgravatarSize'] = 'Размер граватара';
$_lang['setting_modxtalks.mtgravatarSize_desc'] = 'Размер граватара выводимого в комментариях.';
$_lang['setting_modxtalks.defaultAvatar'] = 'Аватар по умолчанию';
$_lang['setting_modxtalks.defaultAvatar_desc'] = 'Ссылка на аватар, который будут по умолчанию у пользователей.';
$_lang['setting_modxtalks.mtDateFormat'] = 'Формат даты';
$_lang['setting_modxtalks.mtDateFormat_desc'] = 'Формат даты. отображаемый в комментариях.';
$_lang['setting_modxtalks.preModarateComments'] = 'Премодерация комментариев';
$_lang['setting_modxtalks.preModarateComments_desc'] = 'Если установленно в - Да, то комментарии изначально попадают на промодерацию. После потверждения менеджером, комментарий выводиться на сайте.';
$_lang['setting_modxtalks.scrubberTop'] = 'Скруббер в топ';
$_lang['setting_modxtalks.scrubberTop_desc'] = 'Отображать скруббер для удобной навигации по комментариям в позиции топ?. Да / Нет';
$_lang['setting_modxtalks.scrubberOffsetTop'] = 'Офсет скруббер';
$_lang['setting_modxtalks.scrubberOffsetTop_desc'] = 'Отступ скрайбера от вехней части экрана. Это нужно, если у вас присутствуют элементы с позицированием fixed, например меню';
$_lang['setting_modxtalks.onlyAuthUsers'] = 'Только авторизованные';
$_lang['setting_modxtalks.onlyAuthUsers_desc'] = 'Оставлять комментарии могут только авторизованные пользователи.';
$_lang['setting_modxtalks.commentLength'] = 'Длина комментария';
$_lang['setting_modxtalks.commentLength_desc'] = 'Максимально допустимая длина комментария в символах.';
$_lang['setting_modxtalks.bbcode'] = 'Включить BBCode';
$_lang['setting_modxtalks.bbcode_desc'] = 'Включить редактор BBCode в комментариях?. Да / Нет';
$_lang['setting_modxtalks.ajax'] = 'Аякс обновление';
$_lang['setting_modxtalks.ajax_desc'] = 'Включить аякс обновление комментариев с сервера?. Да / Нет';
$_lang['setting_modxtalks.highlight'] = 'Подсветка кода';
$_lang['setting_modxtalks.highlight_desc'] = 'Включить подсветку кода Highlight в комментариях?. Да / Нет';
$_lang['setting_modxtalks.highlight'] = 'Тема Highlight';
$_lang['setting_modxtalks.highlight_desc'] = 'Укажите тему оформления подсветки кода. Более детально на сайте <a target="_blank" href="http://softwaremaniacs.org/soft/highlight/en/">highlight</a>.<br />Доступные темы: Default, Dark, FAR, IDEA,Sunburst, Zenburn, Visual Studio,Ascetic,Magula,GitHub,Google Code,Brown Paper,School Book,IR Black,Solarized - Dark,Solarized - Light,Arta,Monokai,XCode,Pojoaque,Rainbow,Tomorrow,Tomorrow Night,Tomorrow Night Bright,Tomorrow Night Blue,Tomorrow Night Eighties';
$_lang['setting_modxtalks.moderator'] = 'Группы модераторов';
$_lang['setting_modxtalks.moderator_desc'] = 'Укажите через запятую группы модераторов, которые которые имею право модерировать комментарии';
// Scrubber
$_lang['modxtalks.start'] = 'Начало';
$_lang['modxtalks.now'] = 'Новые';
$_lang['modxtalks.reply'] = 'Ответить';
$_lang['modxtalks.d_day_ago'] = 'Вчера';
$_lang['modxtalks.d_daysago'] = '[[+d]] дня назад';
$_lang['modxtalks.d_days_ago'] = '[[+d]] дней назад';
$_lang['modxtalks.d_hour_ago'] = '1 час назад';
$_lang['modxtalks.d_hoursago'] = '[[+d]] часа назад';
$_lang['modxtalks.d_hours_ago'] = '[[+d]] часов назад';
$_lang['modxtalks.d_hours_today'] = 'Сегодня';
$_lang['modxtalks.d_minute_ago'] = '1 минуту назад';
$_lang['modxtalks.d_minutes_ago'] = '[[+d]] минуты назад';
$_lang['modxtalks.d_month_ago'] = '1 месяц назад';
$_lang['modxtalks.d_monthsago'] = '[[+d]] месяца назад';
$_lang['modxtalks.d_months_ago'] = '[[+d]] месяцев назад';
$_lang['modxtalks.d_second_ago'] = '1 секунду назад';
$_lang['modxtalks.d_seconds_ago'] = '[[+d]] секунды назад';
$_lang['modxtalks.d_week_ago'] = 'На прошлой неделе';
$_lang['modxtalks.d_weeksago'] = '[[+d]] недели назад';
$_lang['modxtalks.d_weeks_ago'] = '[[+d]] недель назад';
$_lang['modxtalks.d_year_ago'] = 'В прошлом году';
$_lang['modxtalks.d_yearsago'] = '[[+d]] года назад';
$_lang['modxtalks.d_years_ago'] = '[[+d]] лет назад';
// Даты
$_lang['modxtalks.date_year'] = 'год';
$_lang['modxtalks.date_day'] = 'день';
$_lang['modxtalks.date_month'] = 'месяц';
$_lang['modxtalks.date_now'] = 'Только что';
$_lang['modxtalks.date_today'] = 'Сегодня в';
$_lang['modxtalks.date_yesterday'] = 'Вчера в';
$_lang['modxtalks.date_tomorrow'] = 'Завтра в';
$_lang['modxtalks.date_seconds_back'] = '[[+seconds]] секунду назад;[[+seconds]] секунды назад;[[+seconds]] секунд назад';
$_lang['modxtalks.date_minutes_back'] = '[[+minutes]] минуту назад;[[+minutes]] минуты назад;[[+minutes]] минут назад';
$_lang['modxtalks.date_minutes_back_less'] = 'Менее минуты назад';
$_lang['modxtalks.date_hours_back'] = '[[+hours]] час назад;[[+hours]] часа назад;[[+hours]] часов назад;';
$_lang['modxtalks.date_days_back'] = '[[+days]] день назад;[[+days]] дня назад;[[+days]] дней назад;';
$_lang['modxtalks.date_month_back'] = '[[+months]] месяц назад;[[+months]] месяца назад;[[+months]] месяцев назад;';
$_lang['modxtalks.date_years_back'] = '[[+years]] год назад;[[+years]] года назад;[[+years]] лет назад;';
$_lang['modxtalks.date_hours_back_less'] = 'Менее часа назад';
$_lang['modxtalks.today'] = 'Сегодня';
$_lang['modxtalks.month_array'] = '{
     "1" : ["январь", "января", "январе"],
     "2" : ["февраль", "февраля", "феврале"],
     "3" : ["март", "марта", "марте"],
     "4" : ["апрель", "апреля", "апреле"],
     "5" : ["май", "мая", "мае"],
     "6" : ["июнь", "июня", "июне"],
     "7" : ["июль", "июля", "июле"],
     "8" : ["август", "августа", "августе"],
     "9" : ["сентябрь", "сентября", "сентябре"],
    "10" : ["октябрь", "октября", "октябре"],
    "11" : ["ноябрь", "ноября", "ноябре"],
    "12" : ["декабрь", "декабря", "декабре"]
}';
// Bug
$_lang['modxtalks.add_comment_waiting'] = 'Для отправки следующего комментария подождите [[+seconds]] сек.!';
$_lang['modxtalks.already_deleted'] = 'Комментарий уже был удален!';
$_lang['modxtalks.bad_id'] = 'Некорректный идентификатор!';
$_lang['modxtalks.bad_content'] = 'Введите корректное содержимое!';
$_lang['modxtalks.bad_content_length'] = 'Комментарий должен быть не меньше [[+length]] символов';
$_lang['modxtalks.bad_context'] = 'Некорректный контекст!';
$_lang['modxtalks.bad_email'] = 'Введите корректный Email!';
$_lang['modxtalks.bad_name_length'] = 'Имя не может быть меньше [[+length]] символов!';
$_lang['modxtalks.comment_premoderate'] = 'Ваш комментарий успешно отправлен на премодерацию, сразу после проверки модератором он будет опубликован!';
$_lang['modxtalks.delete_timeout'] = 'Время для удаления комментария истекло!';
$_lang['modxtalks.delete_permission'] = 'У вас нет прав на удаление этого комментария!';
$_lang['modxtalks.delet_comment_desc'] = 'Вы действительно хотите удалить этот комментарий?';
$_lang['modxtalks.delete_error'] = 'Ошибка удаления комментария!';
$_lang['modxtalks.empty_name'] = 'Имя не может быть пустым!';
$_lang['modxtalks.edit_timeout'] = 'Время для редактирования комментария ([[+seconds]] сек.) истекло!';
$_lang['modxtalks.edit_permission'] = 'У вас нет прав на редактирование этого комментария!';
$_lang['modxtalks.error_try_again'] = 'Ошибка, повторите попытку позже';
$_lang['modxtalks.empty_content'] = 'Комментарий не может быть пустым!';
$_lang['modxtalks.empty_context'] = 'Контекст не может быть пустым!';
$_lang['modxtalks.empty_email'] = 'Email должен быть заполнен!';
$_lang['modxtalks.empty_conversationId'] = 'Не указан идентификатор темы!';
$_lang['modxtalks.empty_conversation'] = 'Тема не найдена!';
$_lang['modxtalks.edited_by'] = 'отредактировал [[+name]]';
$_lang['modxtalks.go_to_comment'] = 'Перейти к комментарию! ';
$_lang['modxtalks.guest'] = 'Гость';
$_lang['modxtalks.id_not_defined'] = 'Не указан идентификатор!';
$_lang['modxtalks.not_deleted'] = 'Этот комментарий не был удален!';
$_lang['modxtalks.resend_comment_waiting'] = 'Повторная отправка! Подождите [[+seconds]] сек.!';
$_lang['modxtalks.restore_error'] = 'Ошибка восстановления комментария!';
$_lang['modxtalks.successfully_deleted'] = 'Комментарий успешно удален!';
$_lang['modxtalks.successfully_updated'] = 'Комментарий успешно изменен!';
$_lang['modxtalks.successfully_restored'] = 'Комментарий успешно восстановлен!';
$_lang['modxtalks.temppost_err_nfs'] = 'Комментарий не найден!';
$_lang['modxtalks.unallowed_symbols'] = 'Запрещенные символы!';
$_lang['modxtalks.user_exists'] = 'Пользователь с таким Email адресом уже зарегестрированн, пожалуйста, авторизуйтесь чтобы добавить комментарий под этим Email адресом!';
$_lang['modxtalks.unknown_error'] = 'Неизвестная ошибка!';
$_lang['modxtalks.write_comment'] = 'Написать ответ...';
$_lang['modxtalks.save_changes'] = 'Сохранить изменения';
$_lang['modxtalks.cancel'] = 'Отмена';
$_lang['modxtalks.nobody_leave_comment'] = 'Еще пока никто не оставил свой комментарий';
$_lang['modxtalks.comment_approved'] = 'Комментарий утвержден!';
$_lang['modxtalks.ip_ban_success'] = 'IP адресс успешно забанен!';
$_lang['modxtalks.your_name_pl'] = 'Ваше имя';
$_lang['modxtalks.your_email_pl'] = 'Ваш E-mail';
$_lang['modxtalks.deleted_by'] = 'удалил';
